
export  class CommonConstants {
  /**
   * String for input content.
   */
  static readonly OFFSET_X: number = 0;

  /**
   * String for input content.
   */
  static readonly OFFSET_Y: number = -25;

  /**
   * Number for zip level.
   */
  static readonly PERCENT_NINETY: string = '90%';

  /**
   * Number for zip level.
   */
  static readonly PERCENT_FULL: string = '100%';

  /**
   * Number for zip level.
   */
  static readonly FONT_WEIGHT_SEVEN_HUNDRED: number = 700;

  /**
   * Number for zip level.
   */
  static readonly LEAP_YEAR_INPUT: string = '请输入一个年份';

  /**
   * Number for zip level.
   */
  static readonly LEAP_YEAR_YES: string = '该年份是闰年';

  /**
   * Number for zip level.
   */
  static readonly LEAP_YEAR_NO: string = '该年份不是闰年';

  /**
   * Number for zip level.
   */
  static readonly STRING_INPUT: string = '请输入一个字符串';

  /**
   * Number for zip level.
   */
  static readonly PALINDROMIC_STRING_YES: string = '该字符串是回文字符串';

  /**
   * Number for zip level.
   */
  static readonly PALINDROMIC_STRING_NO: string = '该字符串不是回文字符串';

  /**
   * Number for zip level.
   */
  static readonly STRING_PRE: string = '反转结果为：';

  /**
   * The time of toast
   */
  static readonly TOAST_TIME: number = 2000;
}